<?php

namespace JSB\CasinoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StandRepository extends EntityRepository
{
}
