<?php

namespace JSB\CasinoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionRepository extends EntityRepository {

    public function getSolde($idPersonne) {
        return $this->createQueryBuilder("t")
                        ->select("SUM(t.montant)")
                        ->where("t.personne = :id")
                        ->setParameter("id", $idPersonne)
                        ->getQuery()
                        ->getSingleScalarResult()
        ;
    }

}
